### ISSUE TITLE
There is bug with exit command

### ISSUE THREAD

**Issue by lidanger** [julianpaulozzi/LiteDbExplorer#22]
If there is a data file opened, sometimes when click exit menu, the program gives no response. And it seems it's taking much and much memory. When the data file is so large that the memory can not contain it, a crash will appear soon.

**Comment by julianpaulozzi** [comment]
Yes depending on if use will have problems (or many), see [Important Notes](https://github.com/julianpaulozzi/LiteDbExplorer#important-notes).

When exit the application all open dbs dispose is called.

In the future I intend to improve interface blocking by using other threads for some operations.

But I did not see much to do about the memory consumption since the massive consumption is of LiteDB itself and 3rd Party Libraries, [see LiteDB memory issues](https://github.com/mbdavid/LiteDB/search?q=memory&type=Issues). 
I say this after having done several analyzes with dotTrace.

**Comment by julianpaulozzi** [comment]
For now I will close this for not being an unknown issue and as reported [here](https://github.com/julianpaulozzi/LiteDbExplorer#important-notes) is out of my scope.
Any Pull request for review is welcome.
