### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by Dissociable** [julianpaulozzi/LiteDbExplorer#30]
Hello,
As the Table has a HUGE amount of records, "LiteDbExplorer" Can't load all records because it will results "OutOfMemoryException".
The only thing that can fix it is Paging (as i did it in my app lel, however i am using DevExpress components)

Thanks for the work.

**Comment by julianpaulozzi** [comment]
For reference see:
First [Important Notes](https://github.com/julianpaulozzi/LiteDbExplorer#important-notes).
Related issues: #21, #19, #10.

As mentioned in #21, previously I tested skip and take page pagination and profile with [dotMemory](https://www.jetbrains.com/dotmemory/), believe me I saw no real benefit and/or improvement after having already activated UI virtualization.

The large memory consumption comes from LiteDB itself and the AvalonEdit used to view Json to.

The built-in mechanism for populate the records still carries the original project and loading all data to maintain primarily the ability to edit the records without losing reference.

To try to improve this the ideal would be to perform the pages query directly in LiteDB (not in memory since the problem does not seem to be the list view) and lost ability to edit for now.

With version 0.8.4.1 > you can try to use query with [shell commands](https://github.com/mbdavid/LiteDB/wiki/Shell) to view read-only records and see if the problem occurs.

Were you able to solve this problem by using the DevExpress components specifically in this project?

**Comment by Dissociable** [comment]
I'm using latest version of your tool (0.8.3.0) and LiteDB in my App is v4.1.4

TBH That's not DevExpress magic, and yeah i fixed the issue, i have a Customer table that i added more than 1million records to it just to make sure that my app will not have problems in future.
While i was doing it all i noticed something, This code was making the memory usage more than 700MB:
```
col.Find(Query.Or(Query.StartsWith("FirstName", query),
                            Query.StartsWith("LastName", query)));
```
And this code is making the memory usage max. 150MB in the same table (that +1million records table i mean):
```
col.Find(Query.And(Query.All(), Query.Or(Query.StartsWith("FirstName", query),
                            Query.StartsWith("LastName", query))));
```

I don't know if it's the same thing that is the problem you think, but i have no problem with the pagination and BIG database anymore and i'm not sure if that's LiteDB's bug or my misunderstood.

**Comment by julianpaulozzi** [comment]
I would not say it's a bug in LiteDB but its behavior, load many records in "journal mode" consumes a lot of memory even without a UI binding.

In any case, his 1million records use case (or even half of it) seems to fit the issue mentioned in [Important Notes](https://github.com/julianpaulozzi/LiteDbExplorer#important-notes) and is outside my current contribution scope for now.
You can try upgrading to version 0.8.4.1 to use query with shell commands (in collection context menu), wait for a non preview version or better yet submit an pull requests.

Any contribution is welcome.

**Comment by Dissociable** [comment]
I'm trying to add Pagination but i noticed that It's not freeing up some Memory after deleting the items of CollectionReference class lol, the same as it's not freeing up memory after closing a Collection Tab, not even when we close the Database!
Can you please tell me if you Loading records somewhere else after loading Items in CollectionReference?

**Comment by julianpaulozzi** [comment]
Good observation, this is a real problem.
Everything about database is loaded and referenced by Lazy Singleton `Store` class.
This instance is used in many places and events in application, something is holding the references and preventing GC and can be difficult to investigate.
May be a reference stuck in some unreleased event, view model, some XAML access using the `Store Context`... or even some MEF things.

**Comment by julianpaulozzi** [comment]
The big problem is that it's no use just adding pagination, once loaded the references may be being consumed in many parts of UI, null them may cause various other problems.

The core and these problems is the biggest reason for this project at preview.

If it was just simple or even just a little complicated it would already be implemented.

The references have to be tracked to be released at the right time when there is no use anyway.

For this I intended to rewrite the Core using Observable pattern with Reactive Extensions which would make it much simpler to track the listeners/subscribers but I do not have time for this.

**Comment by Dissociable** [comment]
I will try to fix it all, it will be my honor!
but no promises as i have some incomplete projects.

**Comment by julianpaulozzi** [comment]
I will close this for being already notified and due to inactivity.
