### ISSUE TITLE
The editor is not enable to use the DB file in another process (for example, my website)

### ISSUE THREAD

**Issue by EranAvraham** [julianpaulozzi/LiteDbExplorer#41]
**This is a:**
Bug Report

**Version:**
0.8.5.0

**Steps to reproduce:**
open a db file in the explorer, and then use it in another process

**What is expected:**
work with the file with 2 processes without locking the DB

**What is actually happening:**
error

**Any additional comments:**
no

**Comment by julianpaulozzi** [comment]
This is not a bug but a behavior added from version >= v0.8.4.4, see issue #36.

In this GUI once the database is opened it is always connected (never disposes until closed) and all references are always in memory and directly 2 way binded with UI.
This was done to avoid problems mainly when editing and query the data.

**Comment by Ofiraf** [comment]
So unless I'm
missing something This behavior really complicated day to day management of the db.
in order to edit document in the database i can do one of 2 options
1.close the website which obviously unacceptable 
2.copy the database to new location do the changes and override the original database.

**Comment by julianpaulozzi** [comment]
I completely understanding your use case.
Just out of curiosity, how do you connect to the database? Direct on Windows Server by RDP or any other?
Anyway in the next release I will allow this in setting for use at own risk.

**Comment by EranAvraham** [comment]
In my case, the DB file is located in a shared folder (website pc) and I open the file from my laptop.
Allowing this option will help a lot, because right now I can't afford myself to disable the site while the db file is opened in the explorer.
Thanks!

**Comment by Ofiraf** [comment]
Im using rdp directly to the server

**Comment by EranAvraham** [comment]
Think of it like a standard DB explorer, like SQL Server Management Studio. Obviously it doesn't lock the DB when you are connected.
You can just connect and dispose the connection on each query, can't you?

**Comment by julianpaulozzi** [comment]
When using the document screen the interface is directly binded to database collection, no RPC, DTO, change tracker, transaction, active record or something else.
When editing a document is the same case, the difference is that binding is applied only on confirm dialog.
In short, the document screen is dealing with all raw database collection data directly.
In the query screen is another case and is read only.

When I changed the connection mode to exclusive it was just to avoid issues (ike editing old records, since LiteDB no has change notifications). 
Before that I never had problems with my use cases, but I also never used concurrently.

As I said earlier, I have no problem with setting the connection mode as configurable for use at your own risk.
