### ISSUE TITLE
Database Version 6

### ISSUE THREAD

**Issue by informacione** [julianpaulozzi/LiteDbExplorer#9]
I am not able to open my DBLite file. 

Getting:

Failed to open database: Invalid database version: 6

Can you do smth on this?

Thank you in advance

**Comment by julianpaulozzi** [comment]
The error message (Invalid database version: 6) comes from the exception catch when creating an instance of LiteDatabase.
Can you try running this with this DB file to see if it works?

```
public void OpenDatabase(string filePath)
{
    try
    {
        var liteDatabase = new LiteDatabase(filePath);
    }
    catch (Exception e)
    {
        Console.WriteLine("Failed to open database: " + e.Message);
        throw;
    }
}
```

**Comment by informacione** [comment]
Thank you Julian,
Maybe you thing that I am some kind of coder :)
I don't know where to put this code?

**Comment by julianpaulozzi** [comment]
I understand, to run this you would have to have some basic dotnet programming skill.
Are you sure this file is from [LiteDB](https://github.com/mbdavid/LiteDB) version >= 4? How old is this file?

You can also try on other viewers:
A GUI viewer tool: https://github.com/falahati/LiteDBViewer
LiteDB Manager tool : https://darwich.mx/downloads/

**Comment by informacione** [comment]
Yes I have found a way to open it with LiteDBViewer4 - this app converts me to name.v3.db from name.db
Only after this i can open the file with LiteDbExplorer.

The problem is that I can not turn the file back to its original version after making the changes.

Thank you again

**Comment by julianpaulozzi** [comment]
This project relies on and directly uses LiteDB v4 assembly, if core LiteDB v4 is not compatible with older versions this project is not also in a simple way.
You can try an old version of the original project (maybe 0.5), see: https://github.com/JosefNemec/LiteDbExplorer/releases

Another option to try would be to create a new build of this project by doing the dowgrade of the LiteDB DLL version (require dotnet skill), but something must break due to version [Breaking changes](https://github.com/mbdavid/LiteDB/wiki/Changelog#breaking-changes).

Anyway when I have time I will try to test this to see if it works.
I will also take advantage to implement the upgrade process as in LiteDbExplorer.

**Comment by julianpaulozzi** [comment]
Without pretense of supporting versions prior to 4  this issue will be closed.

In version 0.8.0 the error message on the case was improved and in the future a tool will be added for one way migration from version 3 to 4.

If you have more information and/or questions please comment or open a new one.
